# Generated by Django 5.1.7 on 2025-04-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoguessr', '0002_recognitionrequest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='geoguessr/photos'),
        ),
        migrations.AlterField(
            model_name='recognitionrequest',
            name='estimated_date',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
