# Generated by Django 5.1.7 on 2025-04-11 12:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoguessr', '0003_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitionrequest',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='MilitaryPromote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promote_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
