# Generated by Django 5.1.7 on 2025-04-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoguessr', '0004_alter_recognitionrequest_title_militarypromote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
