# Generated by Django 5.2 on 2025-04-12 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoguessr', '0005_user_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitionrequest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 4, 12, 18, 2, 29, 111997, tzinfo=datetime.timezone.utc)),
        ),
    ]
