# Generated by Django 5.2 on 2025-04-14 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoguessr', '0006_alter_recognitionrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='latitude',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='longitude',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='recognitionrequest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 4, 14, 12, 26, 2, 832381, tzinfo=datetime.timezone.utc)),
        ),
    ]
