# Generated by Django 5.2 on 2025-04-14 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoguessr', '0007_alter_answer_latitude_alter_answer_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='latitude',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='longitude',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='recognitionrequest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 4, 14, 12, 37, 20, 949549, tzinfo=datetime.timezone.utc)),
        ),
    ]
